"""Install persistent Sourccey hardware aliases on Raspberry Pi."""

from __future__ import annotations

import os
import shutil
import subprocess
import tempfile
from pathlib import Path
from typing import Callable

PrintFn = Callable[[str], None]

RULES_FILE_PATH = Path("/etc/udev/rules.d/99-sourccey-hardware.rules")

SOURCCEY_UDEV_RULES = """# Sourccey hardware USB port mapping
# Generated by lerobot-robot-sourccey/setup/setup.py

# Servo drivers
SUBSYSTEM=="tty", ENV{ID_PATH}=="platform-1000110000.pcie-pci-0001:01:00.0-usb-0:1.3:1.0", ENV{ID_MM_DEVICE_IGNORE}="1", MODE:="0666", SYMLINK+="robotRightArm"
SUBSYSTEM=="tty", ENV{ID_PATH}=="platform-1000110000.pcie-pci-0001:01:00.0-usb-0:1.4:1.0", ENV{ID_MM_DEVICE_IGNORE}="1", MODE:="0666", SYMLINK+="robotLeftArm"

# Wrist cameras
SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*", ATTR{index}=="0", ENV{ID_PATH}=="platform-xhci-hcd.0-usb-0:1:1.0", SYMLINK+="cameraWristRight"
SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*", ATTR{index}=="0", ENV{ID_PATH}=="platform-xhci-hcd.1-usb-0:2:1.0", SYMLINK+="cameraWristLeft"

# Front cameras
SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*", ATTR{index}=="0", ENV{ID_PATH}=="platform-xhci-hcd.1-usb-0:1:1.0", SYMLINK+="cameraFrontRight"
SUBSYSTEM=="video4linux", KERNEL=="video[0-9]*", ATTR{index}=="0", ENV{ID_PATH}=="platform-xhci-hcd.0-usb-0:2:1.0", SYMLINK+="cameraFrontLeft"
SUBSYSTEM=="video4linux", KERNEL=="video*", ENV{ID_PATH}=="platform-1000110000.pcie-pci-0001:01:00.0-usb-0:1.2.1:1.0", ENV{ID_V4L_CAPABILITIES}==":capture:", ATTR{index}=="0", SYMLINK+="cameraFrontBottom"

# Front lidar
SUBSYSTEM=="tty", KERNEL=="ttyUSB*", ENV{ID_SERIAL}=="Silicon_Labs_CP2102_USB_to_UART_Bridge_Controller_0001", ENV{ID_PATH}=="platform-1000110000.pcie-pci-0001:01:00.0-usb-0:1.2.2:1.0", SYMLINK+="lidarFront"
"""

EXPECTED_DEVICE_ALIASES = (
    "/dev/robotLeftArm",
    "/dev/robotRightArm",
    "/dev/cameraFrontLeft",
    "/dev/cameraFrontRight",
    "/dev/cameraWristLeft",
    "/dev/cameraWristRight",
    "/dev/cameraFrontBottom",
    "/dev/lidarFront",
)


def configure_sourccey_udev(*, print_status: PrintFn, dry_run: bool = False) -> bool:
    """Install the packaged Sourccey udev rules and reload udev."""
    if os.name == "nt" or shutil.which("udevadm") is None:
        print_status("Skipping udev rules: udevadm is unavailable on this system.")
        return True

    use_sudo = hasattr(os, "geteuid") and os.geteuid() != 0
    if use_sudo and shutil.which("sudo") is None:
        print_status("ERROR: sudo is required to install Sourccey udev rules.")
        return False

    prefix = ["sudo"] if use_sudo else []
    if dry_run:
        print_status(f"DRY RUN: install Sourccey udev rules at {RULES_FILE_PATH}")
        return True

    temp_path: Path | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w", encoding="utf-8", delete=False, prefix="sourccey-udev-", suffix=".rules"
        ) as handle:
            handle.write(SOURCCEY_UDEV_RULES)
            temp_path = Path(handle.name)

        subprocess.run(prefix + ["install", "-m", "644", str(temp_path), str(RULES_FILE_PATH)], check=True)
        subprocess.run(prefix + ["udevadm", "control", "--reload-rules"], check=True)
        subprocess.run(prefix + ["udevadm", "trigger"], check=True)
        print_status("Installed Sourccey aliases: " + ", ".join(EXPECTED_DEVICE_ALIASES))
        return True
    except (OSError, subprocess.CalledProcessError) as exc:
        print_status(f"ERROR: failed to install udev rules: {exc}")
        return False
    finally:
        if temp_path is not None:
            temp_path.unlink(missing_ok=True)
